# Generated by Django 2.2 on 2021-08-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_no', models.CharField(blank=True, max_length=10, null=True)),
                ('course_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Examtype',
            fields=[
                ('examtype_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('examtype_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'examtype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('teacher_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'teacher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teacherinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(blank=True, max_length=10, null=True)),
                ('teacher_sex', models.CharField(blank=True, max_length=2, null=True)),
                ('teacher_age', models.IntegerField(blank=True, null=True)),
                ('teacher_date', models.DateField(blank=True, null=True)),
                ('teacher_id', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentserver.Teacher', unique=True)),
            ],
            options={
                'db_table': 'teacherinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=10, null=True)),
                ('student_sex', models.CharField(blank=True, max_length=2, null=True)),
                ('student_age', models.IntegerField(blank=True, null=True)),
                ('student_date', models.DateField(blank=True, null=True)),
                ('student_class', models.CharField(blank=True, max_length=10, null=True)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentserver.Student', unique=True)),
            ],
            options={
                'db_table': 'studentinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teachercourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(blank=True, db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentserver.Course')),
                ('teacher_id', models.ForeignKey(blank=True, db_column='teacher_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentserver.Teacher')),
            ],
            options={
                'db_table': 'teacherCourse',
                'managed': True,
                'unique_together': {('teacher_id', 'course_id')},
            },
        ),
        migrations.CreateModel(
            name='Studentcourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(blank=True, db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentserver.Course')),
                ('student_id', models.ForeignKey(blank=True, db_column='student_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentserver.Student')),
            ],
            options={
                'db_table': 'studentCourse',
                'managed': True,
                'unique_together': {('student_id', 'course_id')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('exam_score', models.FloatField(blank=True, null=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentserver.Course')),
                ('exam_type', models.ForeignKey(blank=True, db_column='examtype_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentserver.Examtype')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentserver.Student')),
            ],
            options={
                'db_table': 'exam',
                'managed': True,
                'unique_together': {('student_id', 'course_id')},
            },
        ),
    ]
