# Generated by Django 2.2 on 2021-08-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('student_id', 'course_id', 'exam_date')},
        ),
    ]
