# Generated by Django 2.2 on 2021-09-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentserver', '0003_auto_20210907_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='vexam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('student_no', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('course_no', models.CharField(blank=True, max_length=50, null=True)),
                ('course_name', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_date', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_score', models.CharField(blank=True, max_length=50, null=True)),
                ('examtype_no', models.CharField(blank=True, max_length=50, null=True)),
                ('examtype_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'v_exam',
                'managed': False,
            },
        ),
    ]
